---
title: "Tables"
author: "Miguel ?ngel Armengol de la Hoz"
output:
  html_document:
    toc: true
    theme: united
---

# Environment

```{r}
library(tableone)
library(magrittr)
library(officer)
library(table1)
library(kableExtra)
library(dplyr)
```

# Table 1 selected_df_fluid

```{r}
label(selected_df_fluid$age_fixed)<-'Age'
label(selected_df_fluid$gender)<-'Gender'
label(selected_df_fluid$weight)<-'Weight'
label(selected_df_fluid$height)<-'Height'
label(selected_df_fluid$unitType)<-'ICU Type'
label(selected_df_fluid$body_surface_area)<-'Body Surface Area'
label(selected_df_fluid$final_elixhauser_score)<-'Elixhauser Comobordity Index'
label(selected_df_fluid$oasis)<-'Oasis Score'
# label(selected_df_fluid$los_icu)<-'ICU LOS'
# label(selected_df_fluid$los_hospital)<-'Hospital LOS'
label(selected_df_fluid$first_hct_6hrs)<-'First Hematocrit 6 hrs.'
label(selected_df_fluid$mean_hct_24_36hrs)<-'First Hematocrit 24-36 hrs.'
label(selected_df_fluid$hosp_mortality)<-'Hospital Mortality'
label(selected_df_fluid$fluid_balance)<-'Total Fluid Balance 24 hrs.'
label(selected_df_fluid$fluid_balance_72)<-'Total Fluid Balance 72 hrs.'
label(selected_df_fluid$leaking_index)<-'Vascular Leak Index.'

vars_in_table1<-c("age_fixed", "gender", "unitType", "weight", "height", "body_surface_area", "leaking_index", "oasis", "final_elixhauser_score", "first_hct_6hrs", "mean_hct_24_36hrs", "hosp_mortality", "fluid_balance","fluid_balance_72")
table1_dataset<-selected_df_fluid[,vars_in_table1]
cat_variables<-rep(NA, length(vars_in_table1))
#stratifyby<-"hosp_mortality"

# detects whether a variable is categorical or not
cont<-1
for (i in 1:length(vars_in_table1) ) {
  if ( n_distinct(table1_dataset[vars_in_table1[i] ])<=10 ) {
    print(i)
    print(vars_in_table1[i])
    print(names(table1_dataset[vars_in_table1[i]]))
    cat_variables[cont]<-names(table1_dataset[vars_in_table1[i]])
    cont<-cont+1
  }
}  
cat_variables<-cat_variables[!is.na(cat_variables)]
table1_base<-print(CreateTableOne(vars = vars_in_table1
                                  #, strata = stratifyby
                                  , factorVars = cat_variables
                                  
    ,data = table1_dataset, addOverall=T),varLabels = T
    ,nonnormal = c('leaking_index'))
# run this in console for html output, the code below uses kableExtra::
starification_cats<-n_distinct(table1_dataset[,stratifyby])
table1_base %>%
  kbl(caption = "Table 1 selected_df_fluid" , align = "c") %>%
  kable_classic_2(full_width = F, html_font = "Cambria")%>%
  add_header_above(c("MIMIC III" = 2 ))
```

# Table 1 selected_df_mortality

```{r}

label(selected_df_mortality$age_fixed)<-'Age'
label(selected_df_mortality$gender)<-'Gender'
label(selected_df_mortality$weight)<-'Weight'
label(selected_df_mortality$height)<-'Height'
label(selected_df_mortality$unitType)<-'ICU Type'
label(selected_df_mortality$body_surface_area)<-'Body Surface Area'
label(selected_df_fluid$leaking_index)<-'Vascular Leak Index.'
label(selected_df_fluid$final_elixhauser_score)<-'Elixhauser Comobordity Index'
label(selected_df_mortality$oasis)<-'Oasis Score'
# label(selected_df_mortality$los_icu)<-'ICU LOS'
# label(selected_df_mortality$los_hospital)<-'Hospital LOS'
label(selected_df_mortality$first_hct_6hrs)<-'First Hematocrit 6 hrs.'
label(selected_df_mortality$mean_hct_24_36hrs)<-'First Hematocrit 24-36 hrs.'
label(selected_df_mortality$hosp_mortality)<-'Hospital Mortality'
label(selected_df_mortality$fluid_balance)<-'Total Fluid Balance 24 hrs.'

vars_in_table1<-c("age_fixed", "gender", "unitType", "weight", "height", "body_surface_area", "leaking_index", "oasis", "final_elixhauser_score", "los_icu", "los_hospital", "first_hct_6hrs", "mean_hct_24_36hrs", "hosp_mortality", "fluid_balance")
table1_dataset<-selected_df_mortality[,vars_in_table1]
cat_variables<-rep(NA, length(vars_in_table1))
#stratifyby<-"hosp_mortality"

# detects whether a variable is categorical or not
cont<-1
for (i in 1:length(vars_in_table1) ) {
  if ( n_distinct(table1_dataset[vars_in_table1[i] ])<=10 ) {
    print(i)
    print(vars_in_table1[i])
    print(names(table1_dataset[vars_in_table1[i]]))
    cat_variables[cont]<-names(table1_dataset[vars_in_table1[i]])
    cont<-cont+1
  }
}  
cat_variables<-cat_variables[!is.na(cat_variables)]
table1_base<-print(CreateTableOne(vars = vars_in_table1
                                  #, strata = stratifyby
                                  , factorVars = cat_variables
                                  
    ,data = table1_dataset, addOverall=T),varLabels = T
    ,nonnormal = c('leaking_index'))
# run this in console for html output, the code below uses kableExtra::
starification_cats<-n_distinct(table1_dataset[,stratifyby])
table1_base %>%
  kbl(caption = "Table 1 selected_df_mortality" , align = "c") %>%
  kable_classic_2(full_width = F, html_font = "Cambria")%>%
  add_header_above(c("MIMIC III" = 2 ))
```
