---
title: "02_training_model"
author: "Miguel Ángel Armengol & Jay Chandra"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  html_notebook:
    code_folding: hide
    number_sections: yes
    theme: flatly
    toc: yes
    toc_float: yes

knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, encoding = encoding, output_file = paste0(substr(inputFile,1,nchar(inputFile)-4)," ",Sys.Date(),'.html')) })
---


# Environment

```{r message=FALSE, warning=FALSE}
require(foreign)
require(ggplot2)
require(MASS)
require(Hmisc)
require(reshape2)
require(boot)
require(pROC)
library(mlbench)
library(MLmetrics)
library(plotly)
library(gbm)
library(xgboost)
library(oddsratio)
library(ggplot2)
library(survey)
library(table1)
library(sandwich)
library(dplyr)
#library(robustHD)
library(mgcv)
library(tidyverse)
library(caret)
center_scale <- function(x) {
    scale(x, scale = FALSE)
}
library(mgcViz)
```

# GAM analysis Fluid Balance

```{r}
# Build the model
model <- gam(fluid_balance_72  ~
                         s(leaking_index) + age_fixed + gender + apache_iv + final_charlson_score + fluid_balance
                         ,data=selected_df_fluid) 
# Make predictions
predictions <- model %>% predict(selected_df_fluid)
# Model performance
data.frame(
  RMSE = RMSE(predictions, selected_df_fluid$fluid_balance_72),
  R2 = R2(predictions, selected_df_fluid$fluid_balance_72)
)
summary(model)
ggplot(selected_df_fluid, aes(leaking_index, fluid_balance_72) ) +
  stat_smooth(method = gam, formula = y ~ s(x)) +
  ggtitle("GAM Model for Leaking Index and Fluid Balance") +
  labs(y="Fluid Balance 72hrs", x = "Leaking Index")

b <- getViz(model)
plot( sm(b, 1) )
```

```{r}
# Build the model
model <- gam(fluid_balance_72_bin  ~
                         s(leaking_index) + age_fixed + gender + apache_iv + final_charlson_score + fluid_balance
                         ,data=selected_df_fluid, family = binomial)
# Make predictions
predictions <- model %>% predict(selected_df_fluid)
# Model performance
data.frame(
  RMSE = RMSE(predictions, selected_df_fluid$fluid_balance_72_bin),
  R2 = R2(predictions, selected_df_fluid$fluid_balance_72_bin)
)
summary(model)
ggplot(selected_df_fluid, aes(leaking_index, fluid_balance_72_bin) ) +
  stat_smooth(method = gam, formula = y ~ s(x)) +
  ggtitle("GAM Model for Leaking Index and Fluid Balance") +
  labs(y="Fluid Balance 72hrs", x = "Leaking Index")

b <- getViz(model)
plot( sm(b, 1) )
```