---
title: "Tables"
author: "Miguel ?ngel Armengol de la Hoz"
output:
  html_document:
    toc: true
    theme: united
---


```{r setup, include=FALSE}
#load the data
#load("C:/BIG FILES/Phenotyping/HemodynamicProjectsDatasetFeb18.RData")
```


```{r}
library(tableone)
library(magrittr)
library(officer)
library(xlsx)
library(table1)
library(kableExtra)
```

# Table 1 

```{r}
vars_in_table1<-c('fluid_balance_72', 'leaking_index','age_fixed','gender','apache_iv','final_charlson_score')
table1_dataset<-selected_df_fluid[,vars_in_table1]
cat_variables<-rep(NA, length(vars_in_table1))
# stratifyby<-"hosp_mortality"
label(table1_dataset$age_fixed)<-'Age'
# detects whether a variable is categorical or not
cont<-1
for (i in 1:length(vars_in_table1) ) {
  if ( n_distinct(table1_dataset[vars_in_table1[i] ])<=10 ) {
    print(i)
    print(vars_in_table1[i])
    print(names(table1_dataset[vars_in_table1[i]]))
    cat_variables[cont]<-names(table1_dataset[vars_in_table1[i]])
    cont<-cont+1
  }
}  
cat_variables<-cat_variables[!is.na(cat_variables)]
table1_base<-print(CreateTableOne(vars = vars_in_table1
                                  # , strata = stratifyby
                                  , factorVars = cat_variables
                                  
    ,data = table1_dataset, addOverall=T),varLabels = T
    ,nonnormal = c('fluid_balance_72', 'leaking_index','final_charlson_score'))
# run this in console for html output, the code below uses kableExtra::
# starification_cats<-n_distinct(table1_dataset[,stratifyby])
table1_base %>%
  kbl(caption = "Table 1 of base model" , align = "c") %>%
  kable_classic_2(full_width = F, html_font = "Cambria")%>%
  add_header_above(c("eICU" =2 ))
```


