---
title: "Tables"
author: "Miguel Angel Armengol de la Hoz"
output:
  html_document:
    toc: true
    theme: united
---


```{r setup, include=FALSE}
#load the data
#load("C:/BIG FILES/Phenotyping/HemodynamicProjectsDatasetFeb18.RData")
```


```{r}
library(tableone)
library(magrittr)
library(officer)
library(table1)
library(kableExtra)
library(dplyr)
```

# Table 1 Amsterdam_72hrFluidBalance

```{r}

label(Amsterdam_72hrFluidBalance$age_fixed)<-'Age'
label(Amsterdam_72hrFluidBalance$gender)<-'Gender'
# label(Amsterdam_72hrFluidBalance$weight)<-'Weight'
# label(Amsterdam_72hrFluidBalance$height)<-'Height'
# label(Amsterdam_72hrFluidBalance$BMI)<-'BMI'
label(Amsterdam_72hrFluidBalance$unitType)<-'ICU Type'
# label(Amsterdam_72hrFluidBalance$body_surface_area)<-'BSA'
#label(Amsterdam_72hrFluidBalance$oasis)<-'Oasis Score'
label(Amsterdam_72hrFluidBalance$unabridgedunitlos)<-'ICU LOS'
label(Amsterdam_72hrFluidBalance$unabridgedhosplos)<-'Hospital LOS'
#label(Amsterdam_72hrFluidBalance$unabridgedactualventdays)<-'Ventilation Days'
label(Amsterdam_72hrFluidBalance$first_hct_6hrs)<-'First Hematocrit 6 hrs.'
label(Amsterdam_72hrFluidBalance$mean_hct_24_36hrs)<-'First Hematocrit 24-36 hrs.'
#label(Amsterdam_72hrFluidBalance$delta_sofa)<-'Δ Sofa'
label(Amsterdam_72hrFluidBalance$hosp_mortality)<-'Hospital Mortality'
#label(Amsterdam_72hrFluidBalance$intakes_total)<-'Total Intake 24 hrs.'
#label(Amsterdam_72hrFluidBalance$intakes_total_72)<-'Total Intake 72 hrs.'

vars_in_table1<-c("age_fixed", "gender", "weight", "height", "BMI", "unitType", "body_surface_area", "oasis", "los_icu", "los_hospital", "unabridgedactualventdays", "first_hct_6hrs", "mean_hct_24_36hrs", "delta_sofa", "hosp_mortality", "intakes_total","intakes_total_72")
table1_dataset<-Amsterdam_72hrFluidBalance[,vars_in_table1]
cat_variables<-rep(NA, length(vars_in_table1))
#stratifyby<-"hosp_mortality"

# detects whether a variable is categorical or not
cont<-1
for (i in 1:length(vars_in_table1) ) {
  if ( n_distinct(table1_dataset[vars_in_table1[i] ])<=10 ) {
    print(i)
    print(vars_in_table1[i])
    print(names(table1_dataset[vars_in_table1[i]]))
    cat_variables[cont]<-names(table1_dataset[vars_in_table1[i]])
    cont<-cont+1
  }
}  
cat_variables<-cat_variables[!is.na(cat_variables)]
table1_base<-print(CreateTableOne(vars = vars_in_table1
                                  #, strata = stratifyby
                                  , factorVars = cat_variables
                                  
    ,data = table1_dataset, addOverall=T),varLabels = T
    ,nonnormal = c('fluid_balance_72', 'leaking_index','final_charlson_score'))
# run this in console for html output, the code below uses kableExtra::
starification_cats<-n_distinct(table1_dataset[,stratifyby])
table1_base %>%
  kbl(caption = "Table 1 Amsterdam_72hrFluidBalance" , align = "c") %>%
  kable_classic_2(full_width = F, html_font = "Cambria")%>%
  add_header_above(c("MIMIC III" = 2 ))
```

# Table 1 selected_df_mortality

```{r}

label(selected_df_mortality$age_fixed)<-'Age'
label(selected_df_mortality$gender)<-'Gender'
label(selected_df_mortality$weight)<-'Weight'
label(selected_df_mortality$height)<-'Height'
label(selected_df_mortality$BMI)<-'BMI'
label(selected_df_mortality$unitType)<-'ICU Type'
label(selected_df_mortality$body_surface_area)<-'BSA'
label(selected_df_mortality$oasis)<-'Oasis Score'
label(selected_df_mortality$los_icu)<-'ICU LOS'
label(selected_df_mortality$los_hospital)<-'Hospital LOS'
label(selected_df_mortality$unabridgedactualventdays)<-'Ventilation Days'
label(selected_df_mortality$first_hct_6hrs)<-'First Hematocrit 6 hrs.'
label(selected_df_mortality$mean_hct_24_36hrs)<-'First Hematocrit 24-36 hrs.'
label(selected_df_mortality$delta_sofa)<-'Δ Sofa'
label(selected_df_mortality$hosp_mortality)<-'Hospital Mortality'
label(selected_df_mortality$intakes_total)<-'Total Intake 24 hrs.'
label(selected_df_mortality$intakes_total_72)<-'Total Intake 72 hrs.'

vars_in_table1<-c("age_fixed", "gender", "weight", "height", "BMI", "unitType", "body_surface_area", "oasis", "los_icu", "los_hospital", "unabridgedactualventdays", "first_hct_6hrs", "mean_hct_24_36hrs", "delta_sofa", "hosp_mortality", "intakes_total","intakes_total_72")
table1_dataset<-selected_df_mortality[,vars_in_table1]
cat_variables<-rep(NA, length(vars_in_table1))
#stratifyby<-"hosp_mortality"

# detects whether a variable is categorical or not
cont<-1
for (i in 1:length(vars_in_table1) ) {
  if ( n_distinct(table1_dataset[vars_in_table1[i] ])<=10 ) {
    print(i)
    print(vars_in_table1[i])
    print(names(table1_dataset[vars_in_table1[i]]))
    cat_variables[cont]<-names(table1_dataset[vars_in_table1[i]])
    cont<-cont+1
  }
}  
cat_variables<-cat_variables[!is.na(cat_variables)]
table1_base<-print(CreateTableOne(vars = vars_in_table1
                                  #, strata = stratifyby
                                  , factorVars = cat_variables
                                  
    ,data = table1_dataset, addOverall=T),varLabels = T
    ,nonnormal = c('fluid_balance_72', 'leaking_index','final_charlson_score'))
# run this in console for html output, the code below uses kableExtra::
starification_cats<-n_distinct(table1_dataset[,stratifyby])
table1_base %>%
  kbl(caption = "Table 1 selected_df_mortality" , align = "c") %>%
  kable_classic_2(full_width = F, html_font = "Cambria")%>%
  add_header_above(c("MIMIC III" = 2 ))
```
