---
title: "01_dataset_creation.Rmd"
output: pdf
---

```{r}
library(bigrquery)
library(summarytools)
library(readr)
library(stringr)
library(sqldf)
library(dplyr)
library(tableone)
library(Hmisc)
library(caret)
library(plotly)
library(table1)
library(Amelia)
library(kableExtra)
options(scipen=999)
```


```{r}
# Sepsis patients without hemodialysis and bleeding
sepsis <- read.csv(file = 'hid_info_death.csv')
sepsis <- sepsis[!duplicated(sepsis$hid), ]
print('Septic patients:')
nrow(sepsis)

# Merge Sepsis and Demographic Data
demographic <- read.csv (file = "septic_hid_info.csv")

demographic<-demographic[!(abs(demographic$height)==1 | abs(demographic$weight) == 1), ]


selected_cohort<-inner_join(demographic,sepsis)
print('Sepsis Patients with Demographic Data')
nrow(selected_cohort)

selected_cohort$birthday = as.Date(selected_cohort$birthday, format = "%Y-%m-%d")
selected_cohort$icuin = as.Date(selected_cohort$icuin, format = "%Y-%m-%d")
selected_cohort$icuout = as.Date(selected_cohort$icuout, format = "%Y-%m-%d")
selected_cohort$death_date = as.Date(selected_cohort$death_date, format = "%Y-%m-%d")
selected_cohort$age = as.numeric((selected_cohort$icuin - selected_cohort$birthday) / 365)
selected_cohort$hosp_mortality = ifelse((selected_cohort$icuout - selected_cohort$icuin) >= (selected_cohort$death_date - selected_cohort$icuin), 1, 0)
selected_cohort$hosp_mortality_offset = ifelse(selected_cohort$death_date - selected_cohort$icuin <= 3, 1, 0)
selected_cohort$hosp_mortality_offset[is.na(selected_cohort$hosp_mortality_offset)] = 0
selected_cohort$hosp_mortality[is.na(selected_cohort$hosp_mortality)] = 0
selected_cohort$body_surface_area = sqrt((selected_cohort$height*selected_cohort$weight) / 3600)

apache_ii <- read.csv(file = 'smr_apache_deidentified.csv')
apache_ii <- apache_ii %>%
  rename(
    dt_apache = dt
    )
selected_cohort <- merge(selected_cohort,apache_ii,by="hid")
selected_cohort$dt_apache <- as.Date(selected_cohort$dt_apache, format = "%Y-%m-%d")
selected_cohort<-selected_cohort[(selected_cohort$icuout - selected_cohort$icuin) >= (selected_cohort$dt_apache - selected_cohort$icuin) & (selected_cohort$dt_apache - selected_cohort$icuin) >= 0, ]
selected_cohort<-selected_cohort[selected_cohort$icuin == selected_cohort$dt_apache, ]

hb_data <- read.csv(file = 'septic_hb_list.csv')
hb_data <- merge(selected_cohort,hb_data,by="hid")
hb_data$dt <- as.Date(hb_data$dt, format = "%Y-%m-%d")
hb_data<-hb_data[(hb_data$icuout - hb_data$icuin) >= (hb_data$dt - hb_data$icuin) & (hb_data$dt - hb_data$icuin) >= 0, ]
hb_data$difference <- hb_data$dt - hb_data$icuin
hb_data <- hb_data[order(hb_data$dt),]
hb_data1temp <- hb_data[hb_data$difference == 0, ]
hb_data2temp <- hb_data[hb_data$difference == 1, ]

io_data <- read.csv(file = 'septic_io_result.csv')
colnames(io_data)[5] <- "io_balance"

io_data <- merge(selected_cohort,io_data,by="hid")
io_data$date <- as.Date(io_data$date, format = "%Y-%m-%d")
io_data<-io_data[(io_data$icuout - io_data$icuin) >= (io_data$date - io_data$icuin) & (io_data$date - io_data$icuin) >= 0, ]
io_data <- io_data[order(io_data$date),]
```


```{r}
io_data24<-sqldf('
WITH added_row_number AS (
  SELECT
    *,
    ROW_NUMBER() OVER(PARTITION BY hid) AS row_number
  FROM io_data
)
SELECT
  hid, io_balance as fluid_balance
FROM added_row_number
WHERE row_number = 1 and io_balance > 0;
')

io_data72<-sqldf('
WITH added_row_number AS (
  SELECT
    *,
    ROW_NUMBER() OVER(PARTITION BY hid) AS row_number
  FROM io_data
)
SELECT
  hid, sum(io_balance) as fluid_balance_72
FROM added_row_number
WHERE row_number = 2 or row_number = 3
group by hid
')

hb_data1 <-sqldf('
WITH added_row_number AS (
  SELECT
    *,
    ROW_NUMBER() OVER(PARTITION BY hid) AS row_number
  FROM hb_data1temp
)
SELECT
  hid, value as value_1, row_number
FROM added_row_number
WHERE row_number == 1
order by hid
')

hb_data2 <-sqldf('
SELECT
  hid, avg(value) as value_2
FROM hb_data2temp
group by hid
order by hid
')

value = merge(hb_data1, hb_data2, by = 'hid')
hb_diff = value
hb_diff$value = hb_diff$value_2- hb_diff$value_1
hb_diff = na.omit(hb_diff)

# We are using a left join to join them
vol_leak_index_dataset<-Reduce(function(...) merge(..., all.x=TRUE), list(
   selected_cohort,
   io_data24,
   io_data72,
   hb_diff
))
```

```{r}
vol_leak_index_dataset<-vol_leak_index_dataset%>%
  mutate(
    leaking_index=((value) / fluid_balance) * body_surface_area * 1561
  )
```

```{r}
hist(vol_leak_index_dataset$leaking_index)
```

```{r eval=FALSE, include=FALSE}
# We are imputing anything outside the 95% interval
extreme_quants<-as.numeric(quantile(vol_leak_index_dataset$leaking_index, c(.05, .95),na.rm = T))

print('Number of patients with imputed data:')
length(which(vol_leak_index_dataset$leaking_index< extreme_quants[1] | vol_leak_index_dataset$leaking_index> extreme_quants[2]))

medLeak = median(vol_leak_index_dataset$leaking_index, na.rm = T)
vol_leak_index_dataset$leaking_index[which(vol_leak_index_dataset$leaking_index< extreme_quants[1] | vol_leak_index_dataset$leaking_index> extreme_quants[2])] = medLeak
```

```{r}
hist(vol_leak_index_dataset$leaking_index)
```


```{r}
selected_df_fluid <- vol_leak_index_dataset%>%dplyr::select(
      hid
    , hosp_mortality
    , hosp_mortality_offset
    , age
    , sex
    , weight
    , fluid_balance
    , fluid_balance_72
    ,value
    ,value_1
    ,value_2
    ,leaking_index
    ,apache2
  )

selected_df_mortality <- vol_leak_index_dataset%>%dplyr::select(
      hid
    , hosp_mortality
    , hosp_mortality_offset
    , age
    , sex
    , weight
    , fluid_balance
    ,value
    ,value_1
    ,value_2
    ,leaking_index
    ,apache2
  )

selected_df_fluid<-selected_df_fluid[complete.cases(selected_df_fluid),]
print('Number of patients after removing incomplete data (fluid):')
nrow(selected_df_fluid)

selected_df_fluid<-selected_df_fluid%>%filter(hosp_mortality_offset == 0)
print('Number of patients after excluding patients with hosp_mort_offset <72hrs:')
nrow(selected_df_fluid)

selected_df_mortality<-selected_df_mortality[complete.cases(selected_df_mortality),]
print('Number of patients after removing incomplete data (mortality):')
nrow(selected_df_mortality)


selected_df_fluid<-selected_df_fluid%>%
  mutate(
     q_leaking_index=as.factor(as.numeric(cut2(leaking_index, g=4)))
)

selected_df_mortality<-selected_df_mortality%>%
  mutate(
     q_leaking_index=as.factor(as.numeric(cut2(leaking_index, g=4)))
)

table(cut2(selected_df_fluid$leaking_index, g=4))
table(cut2(selected_df_mortality$leaking_index, g=4))
```

```{r}
hist(selected_df_fluid$fluid_balance)
```

```{r}
hist(selected_df_fluid$fluid_balance_72)
```
```{r}
table1(~ sex + age + hosp_mortality + value_1 + value_2 +fluid_balance + value + leaking_index + apache2 | q_leaking_index, data=selected_df_mortality)
```

```{r}
write.csv(selected_df_fluid,'selected_df_fluid.csv')
write.csv(selected_df_mortality,'selected_df_mortality.csv')
```

#General Characteristics of SNUH dataset
```{r}
general <- read.csv (file = "genchar.csv")
median_age <- median(general$age, na.rm = TRUE)
mean_sex <- mean(general$male, na.rm = TRUE)
mean_mortality <- mean(selected_df_mortality$hosp_mortality, na.rm = TRUE)
```

