---
title: "01_dataset_creation.Rmd"
output: pdf
---

```{r}
library(bigrquery)
library(summarytools)
library(readr)
library(stringr)
library(sqldf)
library(dplyr)
library(tableone)
library(Hmisc)
library(caret)
library(plotly)
library(table1)
library(Amelia)
library(kableExtra)
options(scipen=999)
```


```{r}
# Sepsis patients without hemodialysis and bleeding
sepsis <- read.csv(file = 'sepsis_list.csv')
sepsis <- sepsis[!duplicated(sepsis$hid), ]
print('Septic patients:')
nrow(sepsis)

# Merge Sepsis and Demographic Data
demographic <- read.csv (file = "age_sex_weight_height.csv")

demographic<-sqldf('
SELECT hid, sex, birthday, dt, 
max (weight) as weight
FROM
demographic
group by hid
')

selected_cohort<-inner_join(demographic,sepsis)
print('Sepsis Patients with Demographic Data')
nrow(selected_cohort)

selected_cohort$birthday = as.Date(selected_cohort$birthday, format = "%Y-%m-%d")
selected_cohort$dt = as.Date(selected_cohort$dt, format = "%Y-%m-%d")
selected_cohort$age = as.numeric((selected_cohort$dt - selected_cohort$birthday) / 365)
```

```{r}
# Input and Output
io_data <- read.csv(file = 'io_data.csv')
colnames(io_data)[5] <- "io_balance"

io_data24<-sqldf('
WITH added_row_number AS (
  SELECT
    *,
    ROW_NUMBER() OVER(PARTITION BY hid) AS row_number
  FROM io_data
)
SELECT
  hid, io_balance as fluid_balance
FROM added_row_number
WHERE row_number = 1 and io_balance > 0;
')

io_data72<-sqldf('
WITH added_row_number AS (
  SELECT
    *,
    ROW_NUMBER() OVER(PARTITION BY hid) AS row_number
  FROM io_data
)
SELECT
  hid, sum(io_balance) as fluid_balance_72
FROM added_row_number
WHERE row_number = 2 or row_number = 3
group by hid
')

hb_data <- read.csv(file = 'hb_data.csv')

hb_data1 <-sqldf('
WITH added_row_number AS (
  SELECT
    *,
    ROW_NUMBER() OVER(PARTITION BY hid) AS row_number
  FROM hb_data
)
SELECT
  hid, value, row_number
FROM added_row_number
WHERE row_number = 1
order by hid
')

hb_data2 <-sqldf('
WITH added_row_number AS (
  SELECT
    *,
    ROW_NUMBER() OVER(PARTITION BY hid) AS row_number
  FROM hb_data
)
SELECT
  hid, value, row_number
FROM added_row_number
WHERE row_number = 2
order by hid
')

value = hb_data2$value - hb_data1$value
hid = hb_data1$hid
hb_diff<- data.frame(hid, value)

# We are using a left join to join them
vol_leak_index_dataset<-Reduce(function(...) merge(..., all.x=TRUE), list(
   selected_cohort,
   io_data24,
   io_data72,
   hb_diff
))
```

```{r}
vol_leak_index_dataset<-vol_leak_index_dataset%>%
  mutate(
    # old definition (NYU Datathon) leaking_index=((mean_hct_24_36hrs/first_hct_6hrs)-1)*body_surface_area*1561
    leaking_index=((value) / fluid_balance) * weight
  )
```

```{r}
hist(vol_leak_index_dataset$leaking_index)
```

```{r eval=FALSE, include=FALSE}
# We are imputing anything outside the 95% interval
extreme_quants<-as.numeric(quantile(vol_leak_index_dataset$leaking_index, c(.025, .975),na.rm = T))

print('Number of patients with imputed data:')
length(which(vol_leak_index_dataset$leaking_index< extreme_quants[1] | vol_leak_index_dataset$leaking_index> extreme_quants[2]))

medLeak = median(vol_leak_index_dataset$leaking_index, na.rm = T)
vol_leak_index_dataset$leaking_index[which(vol_leak_index_dataset$leaking_index< extreme_quants[1] | vol_leak_index_dataset$leaking_index> extreme_quants[2])] = medLeak
```

```{r}
hist(vol_leak_index_dataset$leaking_index)
```


```{r}
selected_df_fluid <- vol_leak_index_dataset%>%dplyr::select(
      hid
    , death
    , age
    , sex
    , weight
    , fluid_balance
    , fluid_balance_72
    ,value
    ,leaking_index
  )

selected_df_fluid<-selected_df_fluid[complete.cases(selected_df_fluid),]
print('Number of patients after removing incomplete data:')
nrow(selected_df_fluid)

selected_df_fluid<-selected_df_fluid%>%
  mutate(
     q_leaking_index=as.factor(as.numeric(cut2(leaking_index, g=2)))
)
print('cutoff points')
unique(cut2(selected_df_fluid$leaking_index, g=2))
```

```{r}
hist(selected_df_fluid$fluid_balance)
```
```{r}
hist(selected_df_fluid$fluid_balance_72)
```
```{r}
table1(~ sex + age + fluid_balance + fluid_balance_72 + value + leaking_index + death, data=selected_df_fluid)
```


