---
title: "02_training_model"
author: "Miguel Ángel Armengol de la Hoz"
date: "May 11, 2019"
output: html_document
---

# Libraries

```{r}
require(foreign)
require(ggplot2)
require(MASS)
require(Hmisc)
require(reshape2)
require(caret)
require(boot)
require(pROC)
```


# Training ordered logit model

```{r}
## fit ordered logit model and store results 'm'
m <- polr(as.factor(delta_sofa) ~ 
            Q_leakingn_index
          +apachescore
          +Final_Charlson_score
          , data = Final_dataset, Hess=TRUE)

## view a summary of the model
summary(m)
```

# Training logistic regression model

```{r}
# Separates data into training and testing data
intrain<-createDataPartition(y=Final_dataset$patientunitstayid,p=0.7,list=FALSE)
training<-Final_dataset[intrain,]
testing<-Final_dataset[-intrain,]
```

```{r}
# trains the logistic model
mod_multiv<-glm(actualhospitalmortality  ~ 
                 Q_leakingn_index
                +apachescore
                +Final_Charlson_score
                 ,family='binomial'
                 ,data = training
                )

mod_multiv

oddsratios_table<-exp(cbind(coef(mod_multiv), confint(mod_multiv)))  
options(scipen=999)
oddsratios_table<-round(oddsratios_table,4)

oddsratios_table<-as.data.frame(oddsratios_table)
colnames(oddsratios_table)[1]<-"OR"

oddsratios_table<-oddsratios_table[order(row.names(oddsratios_table)), ]
boxLabels<-rownames(oddsratios_table)


#write.xlsx(as.data.frame(print(oddsratios_table)), "oddsratios_table.xlsx")

```
```{r}
# trains
sofa_multiv<-glm(sofatotal_day2 ~ 
                 Q_leakingn_index
                +apachescore
                +Final_Charlson_score
                 ,family='gaussian'
                 ,data = Final_dataset
                )

sofa_multiv

sofaratios_table<-exp(cbind(coef(sofa_multiv), confint(sofa_multiv)))  
options(scipen=999)
sofaratios_table<-round(sofaratios_table,4)

sofaratios_table<-as.data.frame(sofaratios_table)
colnames(sofaratios_table)[1]<-"OR"

sofaratios_table<-sofaratios_table[order(row.names(sofaratios_table)), ]
boxLabels<-rownames(sofaratios_table)

```
# Testing the shape of the outcome variables
```{r}
test <- filter(Final_dataset, sofatotal_day1 != 0)
test <- test$sofatotal_day4
hist(test)
```

# Attempts to Validate the Regression Model

```{r}
# Final_dataset<-Final_dataset%>%
#   filter(!is.na(apachescore) & !is.na(Final_Charlson_score) & !is.na(actualhospitalmortality))
# cv.glm (Final_dataset, mod_multiv, K = 2)

auc(Final_dataset$actualhospitalmortality, Final_dataset$apachescore)
Predicted = predict (mod_multiv, testing)
auc(testing$actualhospitalmortality, Predicted)

Predicted = predict (sofa_multiv, testing)
auc(testing$sofatotal_day1, Predicted)
```

